---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: authors.json
  label: Autorzy
  read_only: true
- type: directory
  path: _posts
  label: Blog Posts
  create: all
  match: "**/*.mdx"
  new_doc_ext: mdx
- type: directory
  path: _pages
  label: Strony
  create: documents
  match: "**/*.mdx"
  new_doc_ext: mdx
- type: directory
  path: _wordpress_posts
  label: WordPress (legacy)
  create: none
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - post
upload_dir: public/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
