name: Prettify code

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  stats:
    name: Prettify code
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@38c59cfe9af77dc06f9235182017a6ae416a9223
        id: check
        with:
          reaction: eyes
          trigger: 'TypeofWebBot prettify'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Is this a comment
        if: steps.check.outputs.triggered == 'true'
        uses: xt0rted/pull-request-comment-branch@v1.2.0
        id: comment-branch
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{steps.comment-branch.outputs.head_ref}}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        if: steps.check.outputs.triggered == 'true'
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write .
          only_changed: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
